<a href="https://colab.research.google.com/github/marcelaAn/Estatistica-para-DS-e-ML/blob/main/Amostragem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Amostragem

Carregamento da base de dados

In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
dataset = pd.read_csv('/content/census.csv')

In [3]:
dataset.shape

(32561, 15)

In [4]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [5]:
dataset.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  
32556             0             0             38   United-States   <=50K  
32557             0             0             40   United-States    >50K  
32558             0             0             40   United-States   <=50K  
32559             0             0             20   United-States   <=50K  
32560         15024             0             40   United-States    >50K

Amostragem aleatória simples

In [9]:
df_amostra_aleatoria_simples = dataset.sample(n=100, replace=False)

In [7]:
df_amostra_aleatoria_simples.shape

(100, 15)

In [10]:
df_amostra_aleatoria_simples.head()

age          workclass  final-weight      education  education-num  \
13464   45            Private        162915   Some-college             10   
7150    23            Private        200207        HS-grad              9   
22156   44          Local-gov        433705        HS-grad              9   
17410   43            Private        247880        HS-grad              9   
6226    25   Self-emp-not-inc        266668        HS-grad              9   

            marital-status          occupation    relationship    race    sex  \
13464             Divorced    Transport-moving   Not-in-family   White   Male   
7150              Divorced   Handlers-cleaners       Own-child   White   Male   
22156   Married-civ-spouse     Protective-serv         Husband   White   Male   
17410        Never-married        Craft-repair   Not-in-family   White   Male   
6226         Never-married      Prof-specialty   Not-in-family   White   Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  
13464             0             0             50   United-States   <=50K  
7150              0             0             44   United-States   <=50K  
22156             0             0             52   United-States    >50K  
17410             0             0             40   United-States   <=50K  
6226              0             0             40   United-States   <=50K

In [17]:
def amostragem_aleatoria_simples(dataset, amostras):
  return dataset.sample(n= amostras)

In [18]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [19]:
df_amostra_aleatoria_simples.head()

age      workclass  final-weight      education  education-num  \
650     20        Private        130959   Some-college             10   
12120   39        Private        355468        HS-grad              9   
28803   45   Self-emp-inc        117605        HS-grad              9   
16898   27        Private        114967      Bachelors             13   
23591   18        Private        195372           11th              7   

            marital-status        occupation relationship    race      sex  \
650          Never-married     Other-service    Own-child   White     Male   
12120   Married-civ-spouse             Sales      Husband   White     Male   
28803   Married-civ-spouse   Exec-managerial      Husband   White     Male   
16898        Never-married             Sales    Own-child   White     Male   
23591        Never-married     Other-service    Own-child   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  
650               0             0             20   United-States   <=50K  
12120             0          1887             46   United-States    >50K  
28803             0             0             48   United-States    >50K  
16898             0             0             40   United-States   <=50K  
23591             0             0             20   United-States   <=50K

Amostragem sistemática

In [20]:
dataset.shape

(32561, 15)

In [23]:
len(dataset) // 100

325

In [30]:
random.seed(1)
random.randint(0, 325)

68

In [31]:
68 + 325

393

In [32]:
393 + 325

718

In [33]:
718 + 325

1043

In [35]:
np.arange(68, len(dataset), step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [37]:
def amostragem_sistematica(dataset, amostras):
  intervalo = len(dataset) // amostras
  random.seed(1)
  inicio = random.randint(0, intervalo)
  indices = np.arange(inicio, len(dataset), step=intervalo)
  amostra_sistematica = dataset.iloc[indices]
  return amostra_sistematica

In [38]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100)
df_amostra_sistematica.shape

(100, 15)

In [39]:
df_amostra_sistematica.head()

age      workclass  final-weight      education  education-num  \
68     49   Self-emp-inc        191681   Some-college             10   
393    34      State-gov         98101      Bachelors             13   
718    22        Private        214399   Some-college             10   
1043   44        Private        167005      Bachelors             13   
1368   52        Private        152234        HS-grad              9   

           marital-status        occupation relationship                 race  \
68     Married-civ-spouse   Exec-managerial      Husband                White   
393    Married-civ-spouse   Exec-managerial      Husband                White   
718         Never-married             Sales    Own-child                White   
1043   Married-civ-spouse   Exec-managerial      Husband                White   
1368   Married-civ-spouse   Exec-managerial      Husband   Asian-Pac-Islander   

          sex  capital-gain  capital-loos  hour-per-week  native-country  \
68       Male             0             0             50   United-States   
393      Male          7688             0             45               ?   
718    Female             0             0             15   United-States   
1043     Male          7688             0             60   United-States   
1368     Male         99999             0             40           Japan   

      income  
68      >50K  
393     >50K  
718    <=50K  
1043    >50K  
1368    >50K

Amostragem por grupos

In [41]:
len(dataset) // 10

3256

In [44]:
grupos = []
id_grupo = 0
contagem = 0
for _ in dataset.iterrows():
  grupos.append(id_grupo)
  contagem += 1
  if contagem > 3256:
    contagem = 0
    id_grupo += 1

In [46]:
print(grupos)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [47]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [49]:
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [51]:
dataset['grupo'] = grupos

In [52]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [53]:
dataset.tail()

age      workclass  final-weight    education  education-num  \
32556   27        Private        257302   Assoc-acdm             12   
32557   40        Private        154374      HS-grad              9   
32558   58        Private        151910      HS-grad              9   
32559   22        Private        201490      HS-grad              9   
32560   52   Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
32556             0             0             38   United-States   <=50K   
32557             0             0             40   United-States    >50K   
32558             0             0             40   United-States   <=50K   
32559             0             0             20   United-States   <=50K   
32560         15024             0             40   United-States    >50K   

       grupo  
32556      9  
32557      9  
32558      9  
32559      9  
32560      9

In [110]:
random.randint(0, 9)

7

In [111]:
df_agrupamento = dataset[dataset['grupo'] == 7]
df_agrupamento.shape

(3257, 16)